# Generated by Django 6.0 on 2025-12-06 13:18

import controlodt.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Maquinaria',
                'verbose_name_plural': 'Tipos de Maquinaria',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='perfil/', verbose_name='Foto de perfil')),
                ('firma', models.ImageField(blank=True, null=True, upload_to='firma/', verbose_name='Firma')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('apellidoM', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido materno')),
                ('dni', models.CharField(blank=True, db_index=True, help_text='Sin puntos ni espacios', max_length=20, null=True, unique=True, verbose_name='Carnet de identidad')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s()]{6,20}$', 'Formato de teléfono inválido')], verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
                'permissions': [('usuarios', 'Permiso para usuarios')],
            },
            managers=[
                ('objects', controlodt.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre/Modelo')),
                ('codigo', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Código / Placa / Serie')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('OPERATIVA', 'Operativa'), ('MANTENIMIENTO', 'Mantención requerida'), ('FUERA_SERVICIO', 'Fuera de servicio'), ('DADO_BAJA', 'Dado de baja')], db_index=True, default='OPERATIVA', max_length=20, verbose_name='Estado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinarias_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maquinarias', to='controlodt.tipomaquinaria', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Maquinaria',
                'verbose_name_plural': 'Maquinarias',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroODT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción del trabajo')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ASIGNADA', 'Asignada'), ('EN_EJECUCION', 'En ejecución'), ('REVISION', 'En revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CERRADA', 'Cerrada')], db_index=True, default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('fecha_programada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora programada')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora inicio')),
                ('fecha_termino', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora termino')),
                ('archivo_informe', models.FileField(blank=True, null=True, upload_to='odt/informes/', verbose_name='Archivo informe')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones / notas')),
                ('horas_estimadas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Horas estimadas')),
                ('horas_reales', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Horas reales')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odts_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odts_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a / Ejecutado por')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odts_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odts', to='controlodt.maquinaria', verbose_name='Maquinaria')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odts_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Registro ODT',
                'verbose_name_plural': 'Registros ODT',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('dni__isnull', False)), fields=('dni',), name='unique_dni_when_not_null'),
        ),
        migrations.AddIndex(
            model_name='registroodt',
            index=models.Index(fields=['estado'], name='controlodt__estado_907a91_idx'),
        ),
        migrations.AddIndex(
            model_name='registroodt',
            index=models.Index(fields=['prioridad'], name='controlodt__priorid_02384b_idx'),
        ),
        migrations.AddConstraint(
            model_name='maquinaria',
            constraint=models.UniqueConstraint(fields=('codigo',), name='unique_maquinaria_codigo'),
        ),
    ]
