# Generated by Django 6.0 on 2025-12-21 13:17

import controlodt.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Línea',
                'verbose_name_plural': 'Líneas de trabajo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='perfil/', verbose_name='Foto de perfil')),
                ('firma', models.ImageField(blank=True, null=True, upload_to='firma/', verbose_name='Firma')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('apellidoM', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido materno')),
                ('dni', models.CharField(blank=True, db_index=True, help_text='Sin puntos ni espacios', max_length=20, null=True, unique=True, verbose_name='Carnet de identidad')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s()]{6,20}$', 'Formato de teléfono inválido')], verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
                'permissions': [('usuarios', 'Permiso para usuarios')],
            },
            managers=[
                ('objects', controlodt.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre/Modelo')),
                ('codigo', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Código / Placa / Serie')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Equipo de Trabajo',
                'verbose_name_plural': 'Equipos de Trabajo',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('codigo',), name='unique_maquinaria_codigo')],
            },
        ),
        migrations.CreateModel(
            name='RegistroODT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción del trabajo')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('SOLICITUD', 'En Solicitud'), ('ASIGNADA', 'Asignada'), ('EN_EJECUCION', 'En ejecución'), ('REVISION', 'Revisado'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'R. por Revisión'), ('RECHAZADAA', 'R. en Aprobación'), ('CERRADA', 'Cerrada')], db_index=True, default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('tipo_trabajo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo')], default='PREVENTIVO', max_length=12, verbose_name='Tipo de trabajo')),
                ('correlativo', models.PositiveIntegerField(editable=False, null=True, unique=True)),
                ('n_odt', models.PositiveIntegerField(editable=False, null=True, unique=True)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora programada')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora inicio')),
                ('fecha_termino', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora termino')),
                ('archivo_informe', models.FileField(blank=True, null=True, upload_to='odt/informes/', verbose_name='Archivo informe')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odts_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odts_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odts_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odts', to='controlodt.maquinaria', verbose_name='Maquinaria')),
                ('responsable_ejecucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odts_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de ejecución')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odts_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipoodts', to='controlodt.tipomaquinaria', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Registro ODT',
                'verbose_name_plural': 'Registros ODT',
                'ordering': ['-creado_en'],
                'permissions': [('estadisticas', 'Permiso para Estadisticas')],
            },
        ),
        migrations.CreateModel(
            name='PersonalNecesario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=120, null=True, verbose_name='Categoría')),
                ('trabajador', models.CharField(blank=True, max_length=120, null=True, verbose_name='Trabajador')),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Horas trabajadas')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_necesario', to='controlodt.registroodt')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_falla', models.TextField(blank=True, null=True, verbose_name='Descripción de la falla')),
                ('falla_tipo', models.CharField(choices=[('MECANICO', 'Mecánico'), ('ELECTRICO', 'Eléctrico'), ('TERMICO', 'Térmico'), ('HIDRAULICO', 'Hidráulico'), ('NEUMATICO', 'Neumático'), ('OTRO', 'Otro')], default='OTRO', max_length=12, verbose_name='Falla del equipo')),
                ('hora_inicio_trabajo', models.DateTimeField(blank=True, null=True, verbose_name='Hora de inicio del trabajo')),
                ('hora_fin_trabajo', models.DateTimeField(blank=True, null=True, verbose_name='Hora de finalización del trabajo')),
                ('tareas_realizadas', models.TextField(blank=True, null=True, verbose_name='Tareas realizadas')),
                ('medidas_seguridad', models.TextField(blank=True, null=True, verbose_name='Medidas de seguridad')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('firmado_fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha firma/Finalización')),
                ('ejecutado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odts_ejecutadas', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutado por')),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_ejecucion', to='controlodt.registroodt')),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del repuesto')),
                ('cantidad_utilizada', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cantidad utilizada')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='controlodt.registroodt')),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('dni__isnull', False)), fields=('dni',), name='unique_dni_when_not_null'),
        ),
        migrations.AddIndex(
            model_name='registroodt',
            index=models.Index(fields=['estado'], name='controlodt__estado_907a91_idx'),
        ),
        migrations.AddIndex(
            model_name='registroodt',
            index=models.Index(fields=['prioridad'], name='controlodt__priorid_02384b_idx'),
        ),
    ]
