# Generated by Django 6.0 on 2025-12-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlodt', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroodt',
            name='asignado_a',
        ),
    ]
