# Generated by Django 6.0 on 2025-12-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlodt', '0003_remove_registroodt_asignado_a'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maquinaria',
            options={'ordering': ['tipo', 'nombre'], 'verbose_name': 'Equipo de Trabajo', 'verbose_name_plural': 'Equipos de Trabajo'},
        ),
        migrations.AlterModelOptions(
            name='tipomaquinaria',
            options={'ordering': ['nombre'], 'verbose_name': 'Línea', 'verbose_name_plural': 'Líneas de trabajo'},
        ),
        migrations.RemoveField(
            model_name='registroodt',
            name='horas_estimadas',
        ),
        migrations.RemoveField(
            model_name='registroodt',
            name='horas_reales',
        ),
        migrations.RemoveField(
            model_name='registroodt',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='registroodt',
            name='correlativo',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='registroodt',
            name='n_odt',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='registroodt',
            name='parte_equipo',
            field=models.CharField(default=1, max_length=200, verbose_name='Parte Equipo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='estado',
            field=models.CharField(choices=[('OPERATIVA', 'Operativa'), ('MANTENIMIENTO', 'Mantención requerida'), ('EN_MANTENIMIENTO', 'En mantención'), ('FUERA_SERVICIO', 'Fuera de servicio'), ('DADO_BAJA', 'Dado de baja')], db_index=True, default='OPERATIVA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='registroodt',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ASIGNADA', 'Asignada'), ('EN_EJECUCION', 'En ejecución'), ('REVISION', 'En revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada por Revisión'), ('RECHAZADAA', 'Rechazada en Aprobación'), ('CERRADA', 'Cerrada')], db_index=True, default='BORRADOR', max_length=20, verbose_name='Estado'),
        ),
    ]
