# Generated by Django 6.0 on 2025-12-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlodt', '0004_alter_maquinaria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroodt',
            options={'ordering': ['-creado_en'], 'permissions': [('estadisticas', 'Permiso para Estadisticas')], 'verbose_name': 'Registro ODT', 'verbose_name_plural': 'Registros ODT'},
        ),
        migrations.AlterField(
            model_name='registroodt',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('SOLICITUD', 'En Solicitud'), ('ASIGNADA', 'Asignada'), ('EN_EJECUCION', 'En ejecución'), ('REVISION', 'revisado'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'R. por Revisión'), ('RECHAZADAA', 'R. en Aprobación'), ('CERRADA', 'Cerrada')], db_index=True, default='BORRADOR', max_length=20, verbose_name='Estado'),
        ),
    ]
