# Generated by Django 6.0 on 2025-12-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlodt', '0005_alter_registroodt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroodt',
            options={'ordering': ['-creado_en'], 'permissions': [('estadisticas', 'Permiso para Estadisticas'), ('editar_completo_odt', 'Puede editar completamente una ODT'), ('revisar_odt', 'Puede revisar ODTs'), ('aprobar_odt', 'Puede aprobar ODTs'), ('autorizar_odt', 'Puede autorizar ODTs'), ('detalle_odt', 'Puede ver el detalle odt'), ('enviar_solicitud', 'Puede enviar solicitud'), ('mantenimiento_odt', 'Puede Llenar mantenimiento')], 'verbose_name': 'Registro ODT', 'verbose_name_plural': 'Registros ODT'},
        ),
    ]
